### ISSUE TITLE
Exported meta object uses experimental node feature which logs a warning everytime the libary is imported

### ISSUE THREAD

**Issue by fcortes** [dimaMachina/graphql-eslint#2614]
### Issue workflow progress

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox

     > For example, you can start off by editng the
     > ['basic' example on Stackblitz](https://stackblitz.com/github/B2o5T/graphql-eslint/tree/master/examples/basic).

     > Please make sure the graphql-eslint version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

I was trying to use the `v4.0.0-alpha.5` version for a project where I'm migrating a .eslintrc.js file to the new flat config format and I started getting the following warning when running `eslint`

```
$ yarn lint
(node:25625) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
    at emitExperimentalWarning (node:internal/util:268:11)
    at ModuleLoader.jsonStrategy (node:internal/modules/esm/translators:420:3)
    at callTranslator (node:internal/modules/esm/loader:439:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:445:30)
```

After looking around I found [this PR](https://github.com/dimaMachina/graphql-eslint/pull/2458) where the [`meta.js` file](https://github.com/dimaMachina/graphql-eslint/pull/2458/files#diff-c1aae4606c6c457e20fe6c446f71b1986cefce64e236cc577aa1b0187538d220) is added which includes the following statement

```js
import packageJson from '../package.json' assert { type: 'json' };
```

This seems to use an [experimental feature of node](https://nodejs.org/dist/latest-v22.x/docs/api/esm.html#import-assertions) that seems stable enough but I don't think the current use justifies trying to bypass the warning.

**To Reproduce** Steps to reproduce the behavior:

```dockerfile
FROM node:22

RUN npm init es6 && yarn add \
  "graphql@16.9.0" \
  "@graphql-eslint/eslint-plugin@4.0.0-alpha.5" \
  "eslint@9.11.1"

RUN cat <<'EOF' > eslint.config.js
import * as graphql from "@graphql-eslint/eslint-plugin"
export default [
  {
    files: ['*.graphql'],
    languageOptions: { parser: graphql.parser },
    plugins: { "@graphql-eslint": { rules: graphql.rules } },
    rules: { ...graphql.configs['flat/operations-recommended'].rules }
  },
]
EOF

RUN cat <<'EOF' > queries.graphql
query ShouldCelebrateFirstTransaction {
  shouldCelebrateFirstTransaction
}
EOF

CMD ["yarn", "run", "eslint", "queries.graphql"]
```

```bash
docker run --rm -it $(docker build -q .)
```

<img width="1191" alt="image" src="https://github.com/user-attachments/assets/3a977f68-f34b-4cd6-b804-137d41a8080c">

**Expected behavior**

No warnings when the library is used

**Environment:**

- OS: macOS
- `@graphql-eslint/eslint-plugin`: "4.0.0-alpha.5",
- Node.js: 22.5.1

**Additional context**

Nothing relevant

**Comment by dimaMachina** [comment]
Hi, would you want to submit a PR? we can replace env variable at build time, similar we do for replacing `process.env.NODE_ENV` in tsup https://github.com/dimaMachina/graphql-eslint/blob/129ba5895e67f64ca6020a1dccb253c434e463e5/packages/plugin/tsup.config.ts#L12

**Comment by fcortes** [comment]
Absolutely! It took me a while to understand your suggestion :sweat_smile: but I got something that seems to work fine.
